import { getStore } from '@netlify/blobs';

// Mismo slug que usa la función "articulo" y la portada, para que la URL del
// sitemap coincida con la real del artículo.
function slugify(s) {
  return (s || '')
    .toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80) || 'articulo';
}

// Servida en /sitemap.xml gracias a la redirección en netlify.toml.
// Genera la lista de páginas (portada + cada post publicado) para que
// los buscadores las encuentren, sin tener que mantener el fichero a mano.
// Páginas fijas del sitio (todo lo que no sale de la base de datos de artículos).
// Cuando publiques una guía nueva, añade aquí su fichero — una línea — y entrará
// en el sitemap en el siguiente despliegue. No metas aquí páginas con noindex
// (legales y panel de administración) ni cortar-pdf.html, que es de otro dominio.
const PAGINAS_FIJAS = [
  '/',
  '/aceptar-lo-que-no-puedes-cambiar.html',
  '/ansiedad-ante-los-examenes.html',
  '/ansiedad-por-la-salud.html',
  '/archivo.html',
  '/ayudar-a-alguien-que-sufre.html',
  '/buscar-bibliografia-cientifica.html',
  '/calma-en-5-minutos.html',
  '/calmar-la-ansiedad.html',
  '/citar-en-apa.html',
  '/como-leemos-los-estudios.html',
  '/concentrarte-y-dejar-de-procrastinar.html',
  '/consultorio.html',
  '/controlar-el-enfado.html',
  '/cosas-para-dormir-mejor.html',
  '/crear-habitos-que-duren.html',
  '/cuando-no-tienes-ganas-de-nada.html',
  '/cuando-pierdes-a-alguien.html',
  '/cuando-te-da-un-ataque-de-panico.html',
  '/cuando-te-preocupas-por-todo.html',
  '/cuando-te-sientes-solo.html',
  '/deja-de-compararte.html',
  '/deja-de-darle-vueltas.html',
  '/dejar-de-complacer-a-todos.html',
  '/discutir-mejor-en-pareja.html',
  '/dormir-mejor-en-7-pasos.html',
  '/el-burnout.html',
  '/el-estres-que-no-para.html',
  '/el-miedo-al-que-diran.html',
  '/empieza-aqui.html',
  '/escribir-para-aclararte.html',
  '/gestionar-tus-emociones.html',
  '/gestores-de-referencias.html',
  '/guia-mantas-de-peso.html',
  '/porno-y-habito-compulsivo.html',
  '/adiccion-al-trabajo.html',
  '/nido-vacio.html',
  '/hijos-adultos-que-se-alejan.html',
  '/miedo-a-las-agujas.html',
  '/apretar-los-dientes.html',
  '/limites-con-tus-padres.html',
  '/miedo-a-la-muerte.html',
  '/cuando-recaes.html',
  '/llevarte-mejor-con-tu-cuerpo.html',
  '/la-entrevista-de-trabajo.html',
  '/cuando-te-despiden.html',
  '/misofonia-y-ruidos.html',
  '/el-domingo-por-la-tarde.html',
  '/hacer-amigos-de-adulto.html',
  '/se-me-olvida-todo.html',
  '/preguntas-frecuentes.html',
  '/no-puedo-dormir-esta-noche.html',
  '/redes-sociales-y-animo.html',
  '/ataques-de-ira.html',
  '/hablar-con-tu-medico-salud-mental.html',
  '/volver-a-confiar-en-alguien.html',
  '/sintomas-de-estres.html',
  '/dejar-de-pensar-en-alguien.html',
  '/por-que-lloro-por-todo.html',
  '/miedo-al-fracaso.html',
  '/estres-postraumatico.html',
  '/miedo-al-abandono.html',
  '/aceptar-las-criticas.html',
  '/respirar-para-bajar-la-activacion.html',
  '/relajacion-muscular-progresiva.html',
  '/desconectar-del-trabajo-al-llegar-a-casa.html',
  '/cosas-para-el-estres-del-dia-a-dia.html',
  '/cosas-para-moverte-y-subir-el-animo.html',
  '/test-de-procrastinacion.html',
  '/cosas-para-la-vuelta-a-la-rutina.html',
  '/ansiedad-de-separacion.html',
  '/miedos-nocturnos-en-ninos.html',
  '/premios-y-castigos.html',
  '/cosas-para-la-vuelta-al-cole.html',
  '/cosas-para-el-ruido-y-la-concentracion.html',
  '/test-de-personalidad.html',
  '/mis-resultados.html',
  '/cosas-para-el-tdah-en-adultos.html',
  '/cosas-para-el-dolor-cronico.html',
  '/dejar-el-movil-por-la-noche.html',
  '/cuando-tu-hijo-se-va-de-casa.html',
  '/cuando-te-comparan-con-otros.html',
  '/volver-a-salir-despues-de-mucho-tiempo.html',
  '/no-me-toman-en-serio.html',
  '/test-de-ataques-de-panico.html',
  '/test-rapido-alcohol.html',
  '/cosas-primeras-semanas-con-un-bebe.html',
  '/cosas-para-tus-padres-mayores.html',
  '/miedo-al-miedo.html',
  '/volver-a-confiar-en-tu-cuerpo.html',
  '/decir-que-no-en-el-trabajo.html',
  '/mudarse-a-otro-pais.html',
  '/no-me-gusta-mi-trabajo-y-no-puedo-dejarlo.html',
  '/test-rapido-ansiedad-depresion.html',
  '/test-de-dependencia-del-tabaco.html',
  '/cosas-para-dejar-de-fumar.html',
  '/cosas-para-que-estudie-mejor.html',
  '/acompanar-a-alguien-en-terapia.html',
  '/hablar-con-alguien-que-bebe-demasiado.html',
  '/que-decir-a-alguien-en-duelo.html',
  '/ayudar-a-alguien-que-no-quiere-ayuda.html',
  '/que-regalar-a-alguien-que-lo-pasa-mal.html',
  '/trabajar-en-casa-sin-reventar.html',
  '/test-de-sintomas-fisicos.html',
  '/test-de-estres-postraumatico.html',
  '/no-puedo-llorar.html',
  '/compararte-en-redes-sociales.html',
  '/problemas-con-mis-hermanos.html',
  '/no-tengo-tiempo-para-nada.html',
  '/cosas-que-ayudan-con-la-ansiedad.html',
  '/cosas-que-ayudan-cuando-estas-bajo.html',
  '/cafeina-y-ansiedad.html',
  '/duermo-demasiado.html',
  '/me-cuesta-pedir-ayuda.html',
  '/si-alguien-te-dice-que-quiere-morir.html',
  '/no-puedo-parar-de-pensar-por-la-noche.html',
  '/no-se-que-hacer-con-mi-vida.html',
  '/no-me-gusta-mi-cuerpo.html',
  '/buscar-sintomas-en-internet.html',
  '/mi-hijo-me-contesta-mal.html',
  '/volver-al-trabajo-en-septiembre.html',
  '/perdonarse-a-uno-mismo.html',
  '/me-siento-vacio.html',
  '/miedo-a-salir-de-casa.html',
  '/celos-y-revisar-el-movil.html',
  '/primera-sesion-psicologo.html',
  '/no-me-acuesto-aunque-tengo-sueno.html',
  '/volver-a-empezar.html',
  '/ataque-de-ansiedad-por-la-noche.html',
  '/autoestima-en-los-ninos.html',
  '/como-saber-si-tengo-ansiedad.html',
  '/mi-pareja-no-me-habla.html',
  '/no-siento-nada.html',
  '/ayudar-a-alguien-con-ansiedad.html',
  '/terapia-online.html',
  '/decir-lo-que-piensas.html',
  '/mudarse-de-casa.html',
  '/mi-hijo-no-estudia.html',
  '/ansiedad-en-sitios-cerrados.html',
  '/acompanar-en-una-enfermedad-grave.html',
  '/rabietas-y-enfados-de-los-ninos.html',
  '/registro-abc.html',
  '/miedo-al-dentista.html',
  '/perdida-gestacional.html',
  '/ansiedad-por-la-salud-de-los-hijos.html',
  '/cuando-desaparecen-sin-explicacion.html',
  '/vivir-solo-por-primera-vez.html',
  '/miedo-a-envejecer.html',
  '/cuando-se-acaba-una-amistad.html',
  '/no-soporto-mi-trabajo.html',
  '/hermanos-y-cuidar-a-los-padres.html',
  '/diagnostico-de-un-hijo.html',
  '/hablar-de-la-muerte-con-ninos.html',
  '/dormir-en-pareja.html',
  '/sentirse-estancado.html',
  '/volver-a-estudiar-de-adulto.html',
  '/test-de-alcohol.html',
  '/beber-menos-sin-dejarlo.html',
  '/mi-pareja-bebe-demasiado.html',
  '/la-envidia.html',
  '/ansiedad-al-telefono.html',
  '/familia-politica.html',
  '/dinero-en-pareja.html',
  '/terapia-conductual-preguntas.html',
  '/guiones-conversaciones-dificiles.html',
  '/morderse-las-unas.html',
  '/miedo-a-vomitar.html',
  '/cuando-el-cuerpo-avisa.html',
  '/pantallas-y-adolescentes.html',
  '/empezar-un-trabajo-nuevo.html',
  '/soltar-el-rencor.html',
  '/test-de-depresion.html',
  '/ansiedad-social.html',
  '/celos-entre-hermanos.html',
  '/acompanar-demencia.html',
  '/cuando-niega-el-problema.html',
  '/carga-mental.html',
  '/jubilacion.html',
  '/autolesiones-adolescentes.html',
  '/diagnostico-enfermedad-grave.html',
  '/obsesiones-y-toc.html',
  '/lo-dejo-o-sigo.html',
  '/ansiedad-en-el-embarazo.html',
  '/no-poder-tener-hijos.html',
  '/no-quiere-ir-al-colegio.html',
  '/gritar-menos-a-los-hijos.html',
  '/compras-compulsivas.html',
  '/vivir-lejos-de-casa.html',
  '/libros-recomendados.html',
  '/separacion-con-hijos.html',
  '/agotamiento-de-padres.html',
  '/alta-sensibilidad.html',
  '/pareja-con-depresion.html',
  '/tests.html',
  '/test-de-ansiedad.html',
  '/miedo-a-volar.html',
  '/despues-de-un-accidente.html',
  '/volver-al-trabajo-tras-una-baja.html',
  '/alcohol-y-ansiedad.html',
  '/miedo-a-conducir.html',
  '/juego-y-apuestas.html',
  '/duelo-por-suicidio.html',
  '/menopausia-y-animo.html',
  '/donde-pedir-ayuda.html',
  '/tdah-en-adultos.html',
  '/dolor-cronico.html',
  '/ansiedad-por-dinero.html',
  '/acoso-laboral.html',
  '/duelo-por-una-mascota.html',
  '/oposiciones-sin-quemarte.html',
  '/depresion-posparto.html',
  '/sueno-de-los-ninos.html',
  '/superar-una-fobia.html',
  '/comer-por-ansiedad.html',
  '/sobrecarga-del-cuidador.html',
  '/dejar-de-fumar.html',
  '/insomnio.html',
  '/sindrome-del-impostor.html',
  '/elegir-psicologo.html',
  '/ayudar-a-un-hijo-adolescente.html',
  '/hablar-en-publico.html',
  '/hablarte-mejor.html',
  '/la-culpa.html',
  '/la-dependencia-emocional.html',
  '/leer-un-metaanalisis.html',
  '/leer-un-paper.html',
  '/los-celos.html',
  '/mejorar-tu-autoestima.html',
  '/menos-movil-cosas.html',
  '/menos-movil-mas-cabeza.html',
  '/menos-perfeccionismo.html',
  '/moverte-en-casa.html',
  '/para-estudiantes.html',
  '/pensamientos-que-no-quieres-tener.html',
  '/poner-limites.html',
  '/reconstruir-la-confianza-en-pareja.html',
  '/recursos-gratuitos-psicologia.html',
  '/rincon-para-concentrarte.html',
  '/sobre-mi.html',
  '/superar-una-ruptura.html',
  '/temas.html',
  '/tomar-decisiones-dificiles.html',
  '/un-rincon-de-calma.html',
  '/vencer-la-timidez.html',
  '/volver-a-la-rutina.html',
];

export default async (req) => {
  const url = new URL(req.url);
  const base = `${url.protocol}//${url.host}`;
  const urls = PAGINAS_FIJAS.map((ruta) => ({ loc: `${base}${ruta}` }));

  try {
    const posts = getStore('posts');
    const { blobs } = await posts.list();
    for (const b of blobs) {
      const post = await posts.get(b.key, { type: 'json' });
      if (post?.id) {
        urls.push({
          loc: `${base}/articulo/${slugify(post.titulo)}/${encodeURIComponent(post.id)}`,
          lastmod: (post.fechaPublicacion || post.fecha || '').slice(0, 10) || undefined,
        });
      }
    }
  } catch (err) {
    console.error('sitemap: error interno:', err);
  }

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    (u) => `  <url>
    <loc>${u.loc}</loc>${u.lastmod ? `\n    <lastmod>${u.lastmod}</lastmod>` : ''}
  </url>`
  )
  .join('\n')}
</urlset>`;

  return new Response(xml, {
    status: 200,
    headers: { 'content-type': 'application/xml; charset=utf-8' },
  });
};
